trigger:
  branches:
    include:
    - master
  paths:
    include:
    - ml
    exclude:
    - ml/experiments

variables:
- name: infraArmTemplate
  value: ml/infra/deploy.json
- name: datastoreCfg
  value: ml/infra/setup/datastore.cfg
- name: datastoreSetupPy
  value: ml/infra/setup/datastore.py

stages:
- stage: dev
  variables:
  - group: mlops-dev
  jobs:
  - job: infra
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        overrideParameters: -tenantId $(tenantId)
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(pipelineServiceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroup)
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: $(infraArmTemplate)
        csmParametersFile: $(infraArmTemplateParameterFile)
        deploymentMode: 'Incremental'
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            python $(datastoreSetupPy) -f $(datastoreCfg) -s '{"subscriptionId":"$(subscriptionId)", "resourceGroup":"$(resourceGroup)", "storageAccountKey":"$(storageAccountKey)"}'
          failOnStderr: true
    # - task: PythonScript@0
    #   inputs:
    #     scriptSource: 'filePath'
    #     scriptPath: $(datastoreSetupPy)
    #     arguments: '{"subscriptionId":"$(subscriptionId)", "resourceGroup":"$(resourceGroup)", "storageAccountKey":"$(storageAccountKey)"}'
    #     failOnStderr: true
  # - job: build
  # - job: unit test

# - stage: test
#   jobs:
#     - job: deploy
#       steps:
#         - deploy azure workspace resources
#         - deploy pipeline endpoints
#           - preprocessing
#           - score
#         - deploy monitoring resources
#     - job: integration test
#       steps:
#         - test preprocessing pipeline
#         - test score pipeline
#     - job: notification
#       steps:
#         - send notification for approval gate

# - stage: prod
#   jobs:
#     - job: deploy
#       steps:
#         - deploy azure workspace resources
#         - deploy pipeline endpoints
#           - preprocessing
#           - score
#         - deploy monitoring resources

