trigger:
  branches:
    include:
    - master
  paths:
    include:
    - ml
    exclude:
    - ml/experiments

stages:
- stage: dev
  jobs:
  # - job: build
  # - job: unit test
  - job: deploy
    variables:
    - group: mlops-dev
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        overrideParameters: --tenantId $(tenantId)
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'azrm'
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'dp100'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: $(infraArmTemplate)
        csmParametersFile: $(infraArmTemplateParameterFile)
        deploymentMode: 'Incremental'
        deploymentName: 'test'

# - stage: test
#   jobs:
#     - job: deploy
#       steps:
#         - deploy azure workspace resources
#         - deploy pipeline endpoints
#           - preprocessing
#           - score
#         - deploy monitoring resources
#     - job: integration test
#       steps:
#         - test preprocessing pipeline
#         - test score pipeline
#     - job: notification
#       steps:
#         - send notification for approval gate

# - stage: prod
#   jobs:
#     - job: deploy
#       steps:
#         - deploy azure workspace resources
#         - deploy pipeline endpoints
#           - preprocessing
#           - score
#         - deploy monitoring resources

