trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - experiments

variables:
- name: infraArmTemplate
  value: infra/deploy.json
- name: keyVaultTenantId
  value: 3d2eac2c-81ec-4951-b44e-e8e628a011b9

stages:
- stage: dev
  variables:
  - group: mlops-dev
  - name: infraArmTemplateParameterFile
    value: infra/parameters/dev.json
  jobs:
  - job: infra
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Create ML orkspace'
      inputs:
        overrideParameters: -tenantId $(keyVaultTenantId)
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'azrm-pep-dev-rg'
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroup)
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: $(infraArmTemplate)
        csmParametersFile: $(infraArmTemplateParameterFile)
        deploymentMode: 'Incremental'
    - task: Bash@3
      displayName: 'Setup Datastores'
      inputs:
        targetType: 'inline'
        script: |
          pip install -r requirements.txt
          python infra/setup/datastore.py -f infra/setup/datastore.cfg \
            -s '{"subscriptionId":"$(subscriptionId)", "resourceGroup":"$(resourceGroup)", \
                 "storageAccountKey":"$(storageAccountKey)", \
                 "saSubscriptionId": "$(saSubscriptionId)", \
                 "saResourceGroup": "$(saResourceGroup)" \
                }'
        failOnStderr: true
    # - task: PythonScript@0
    #   inputs:
    #     scriptSource: 'filePath'
    #     scriptPath: $(datastoreSetupPy)
    #     arguments: '{"subscriptionId":"$(subscriptionId)", "resourceGroup":"$(resourceGroup)", "storageAccountKey":"$(storageAccountKey)"}'
    #     failOnStderr: true
  # - job: build
  # - job: unit test

# - stage: test
#   jobs:
#     - job: deploy
#       steps:
#         - deploy azure workspace resources
#         - deploy pipeline endpoints
#           - preprocessing
#           - score
#         - deploy monitoring resources
#     - job: integration test
#       steps:
#         - test preprocessing pipeline
#         - test score pipeline
#     - job: notification
#       steps:
#         - send notification for approval gate

# - stage: prod
#   jobs:
#     - job: deploy
#       steps:
#         - deploy azure workspace resources
#         - deploy pipeline endpoints
#           - preprocessing
#           - score
#         - deploy monitoring resources

