# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'azrm'
    subscriptionId: 'fbfc77ed-6780-41e8-8a3f-21e1083cd1e2'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'ml/infra/deploy.json'
    csmParametersFile: 'ml/infra/parameter/dev.json'
    deploymentMode: 'Incremental'