parameters:
- name: tenantId
  type: string
- name: serviceConnection
  type: string
- name: subscriptionId
  type: string
- name: resourceGroup
  type: string
- name: location
  type: string
- name: infraArmTemplate
  type: string
- name: infraArmTemplateParameterFile
  type: string
- name: workspaceSetupSecretsMap
  type: string

jobs:
- job: infra
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Create ML Workspace'
    inputs:
      overrideParameters: -tenantId ${{parameters.tenantId}}
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: ${{parameters.serviceConnection}} #'azrm-pep-dev-rg'
      subscriptionId: ${{parameters.subscriptionId}}
      action: 'Create Or Update Resource Group'
      resourceGroupName: ${{parameters.resourceGroup}}
      location: ${{parameters.location}}
      templateLocation: 'Linked artifact'
      csmFile: ${{parameters.infraArmTemplate}}
      csmParametersFile: ${{parameters.infraArmTemplateParameterFile}}
      deploymentMode: 'Incremental'
  - script: |
      pip install -r requirements.txt
      python infra/workspace.py -f infra/config/workspace.cfg -s '${{parameters.workspaceSetupSecretsMap}}'
    displayName: "Setup ML Workspace"
    env:
      PYTHONPATH: $(Build.SourcesDirectory)