trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - experiments

variables:
- name: infraArmTemplate
  value: infra/deploy.json

stages:
- stage: dev
  variables:
  - group: mlops-dev
  - name: infraArmTemplateParameterFile
    value: infra/config/deploy.parameters.dev.json
  - name: serviceConnection
    value: azrm-pep-dev-rg
  jobs:
  - template: templates/workspace-infra.yaml
    parameters:
      tenantId: $(tenantId)
      serviceConnection: $(serviceConnection)
      subscriptionId: $(subscriptionId)
      resourceGroup: $(resourceGroup)
      location: $(location)
      infraArmTemplate: $(infraArmTemplate)
      infraArmTemplateParameterFile: $(infraArmTemplateParameterFile)
      workspaceSetupSecretsMap: '{"storageAccountKey":"$(storageAccountKey)"}'
  # - job: build
  # - job: unit test

# - stage: test
#   jobs:
#     - job: deploy
#       steps:
#         - deploy azure workspace resources
#         - deploy pipeline endpoints
#           - preprocessing
#           - score
#         - deploy monitoring resources
#     - job: integration test
#       steps:
#         - test preprocessing pipeline
#         - test score pipeline
#     - job: notification
#       steps:
#         - send notification for approval gate

# - stage: prod
#   jobs:
#     - job: deploy
#       steps:
#         - deploy azure workspace resources
#         - deploy pipeline endpoints
#           - preprocessing
#           - score
#         - deploy monitoring resources

